name: devtool_logger
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  logger: any
  devtools_extensions: ^0.5.0
  devtools_app_shared: ^0.5.0
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  logger:
    path: ../

flutter:
  uses-material-design: true
